# Generated by Django 5.0.6 on 2024-06-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawTransaction",
            fields=[
                (
                    "transaction_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("transaction_date", models.DateField()),
                ("transaction_time", models.TimeField(max_length=255)),
                ("transaction_qty", models.IntegerField()),
                ("store_id", models.IntegerField()),
                ("store_location", models.CharField(max_length=255)),
                ("product_id", models.IntegerField()),
                ("unit_price", models.FloatField()),
                ("product_category", models.CharField(max_length=255)),
                ("product_type", models.CharField(max_length=255)),
                ("product_detail", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "raw_transaction",
            },
        ),
    ]
