# Generated by Django 5.0.6 on 2024-06-25 04:58

from django.db import migrations
import pandas as pd


def load_xlsx_data(apps, schema_editor):
    RawTransaction = apps.get_model("transactions", "RawTransaction")

    # Read the Excel file into a DataFrame
    df = pd.read_excel("dataset/coffee_shop_sales.xlsx")

    # Create a list of RawTransaction instances
    raw_transactions = [
        RawTransaction(
            transaction_date=row["transaction_date"],
            transaction_time=row["transaction_time"],
            transaction_qty=row["transaction_qty"],
            store_id=row["store_id"],
            store_location=row["store_location"],
            product_id=row["product_id"],
            unit_price=row["unit_price"],
            product_category=row["product_category"],
            product_type=row["product_type"],
            product_detail=row["product_detail"],
        )
        for _, row in df.iterrows()
    ]

    # Bulk create the RawTransaction instances
    RawTransaction.objects.bulk_create(raw_transactions)


def delete_table_data(apps, schema_editor):
    RawTransaction = apps.get_model("transactions", "RawTransaction")
    RawTransaction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_xlsx_data, reverse_code=delete_table_data),
    ]
